document.addEventListener("DOMContentLoaded", function() {
    const topPhrases = [
        "Where is the strangest place you've ever masturbated?",
        "Who is your #1 person you dream to have sex with?",
        "Have you ever been caught masturbating?",
        "What's the kinkiest thought you've ever had about someone?",
        "What is an awkward situation you have found yourself aroused in?",
        "Have you ever fantasized about a teacher or authority figure? Who was it and why?",
        "Do you have a fetish/kink?",
        "What fantasies do you get when masturbating?",
        "What is a sexual fantasy you have?",
        "What spot on your body is most sensitive?",
        "What places do you like to be touched during pleasing?",
        "Would you prefer to dominate in bed or to be dominated in bed?",
        "What is your favorite body part for a person to suck on?",
        "What would be your favorite sex toy to use on the other player?",
        "What's the kinkiest thing you've ever done?",
        "What's the hottest sex dream you've ever had?",
        "Whats one thing someone can do that would make you immediately orgasm?",
        "Which is your favorite kind of sex: soft, slow, and sweet or aggressive, fast, and feisty?",
        "If you had a free pass to hook up with one celebrity, who would it be and why?",
        "If you could do anything to the other player, what would it be?",
        "What item of clothing do you think the other player looks sexiest in?",
        "Who would be in your dream orgy?",
        "What do you remember most about the first time you ever masturbated?",
        "Who is the weirdest person you've had a sex dream about?",
        "Would you ever want to watch the other player have sex with someone else? Who would it be?",
        "What's one sex toy you want someone to try on you?",
        "What would be your dream role-play scenario?",
        "What kind of role-play do you fantasise?",
        "What do you usually get aroused from?",
        "Have you ever gotten turned on at work/school? What did you do about it?",
        "Whats the worst place you have found yourself high/aroused?",
        "What's something I do that isn't sexual but turns you on?",
        "Do you prefer using your tongue or fingers on someone?",
        "Have you ever turned down a sexual opportunity and regretted it?",
        "What's the sexiest song you've ever heard? What about it turns you on?",
        "What's the most amount of times you've orgasmed in a day?",
        "If the other player were handcuffed to the bed, what would you do to them?",
        "What's something dirty you've always been too shy to say?",
        "Is there something you've seen in a steamy movie that you'd like to try?",
        "What kind of foreplay would you like to try?",
        "How often do you masturbate?",
        "What's your favorite text or response when sexting with someone?",
        "What do you think the sexiest part of your body is?",
        "What do you think the sexiest part of the other player's body is?",
        "What is your favorite scene in a dirty book movie? What about it turns you on?",
        "What's your biggest turn-off?",
        "What's your biggest turn-on?",
        "When was the last time you lied?",
        "When was the last time you cried?",
        "What's your biggest fear?",
        "What's your biggest fantasy?",
        "Who's the last person you searched on Instagram?",
        "What's the strangest thing you've ever eaten?",
        "What's your relationship dealbreaker?",
        "What's a secret you've never told anyone?",
        "Who was your first celebrity crush?",
        "Have you ever cheated in an exam?",
        "What's your biggest insecurity?",
        "What's the biggest mistake you've ever made?",
        "What's one thing you hate people knowing about you?",
        "What's the worst thing anyone's ever done to you?",
        "What's the best thing anyone's ever done for you?",
        "What's your worst habit?",
        "What's the biggest misconception about you?",
        "What's one thing you wish people knew about you?",
        "What's the best piece of advice you've been given?",
        "Who's your most recent crush?",
        "What have you purchased that's been the biggest waste of money?",
        "How would you rate your looks on a scale of 1 to 10?",
        "What celebrity do you look up to?",
        "If you could be one celebrity for a day, who would it be?",
        "If you could do any job in the world, what would it be?",
        "What's your dream life?",
        "What do you value the most - money, fame, success, friends, family, etc?",
        "What’s your biggest red flag?",
        "What’s one movie you’re embarrassed to admit you enjoy?",
        "What is your most favorite smut book/movie?",
        "Name something you can’t live without.",
        "If you could marry any celebrity, who would it be and why?",
        "What is your love language?",
        "Where's the weirdest place you peed?",
        "Have you ever peed in the shower?",
        "What's the strangest dream you've had?",
        "What's one thing you only do when you're alone?",
        "What's the strangest rumour you've heard about yourself?",
        "What's your favourite gross food combination?",
        "What's the weirdest lie you've ever told?",
        "Do you have any fake social media accounts?",
        "Have you ever peed in the pool?",
        "What gives you the ick?",
        "What do you do that could give someone else the ick?",
        "What's the weirdest thing you've ever eaten?",
        "What is a weird food that you love?",
        "What was your biggest childhood fear?",
        "Did you ever have a crush on an adult?",
        "What’s the weirdest thing you’re obsessed with on TikTok?",
        "What’s the most surprising thing in your bag right now?",
        "Who is your weird celebrity crush?",
        "What’s the weirdest habit you have when you’re alone?",
        "Do you have any rare desires?",
        "What's something you're glad your family doesn't know about you?",
        "Have you ever cheated on someone?",
        "What's the worst thing you've ever done?",
        "What are your thoughts on polyamory?",
        "What's the worst intimate experience you've ever had?",
        "What's the best intimate experience you've ever had?",
        "Have you ever broken the law?",
        "If you had to never speak to someone again, who would it be and why?",
        "Have you ever stayed friends with someone because it benefitted you beyond just the friendship?",
        "Who would you like to kiss the most?",
        "Have you ever had a run in with the law?",
        "What's the worst thing you've ever said to anyone?",
        "Have you ever been caught doing something you shouldn't have?",
        "What's your biggest regret?",
        "Have you ever said something you regret about someone?",
        "What's the most trouble you've been in?",
        "When did you last masturbate?",
        "What's the worst thing you've lied about?",
        "What's one thing you wish you'd lied about?",
        "Name a time you think you were a bad friend.",
        "If you had to cut one friend out of your life, who would it be?",
        "What's your guilty pleasure?",
        "If you had the chance to marry anyone, who would it be?",
        "Do you have a favourite friend?",
        "What's your biggest turn on?",
        "If you could swap lives with someone, who would it be?",
        "Have you ever told a lie about your BFF to make yourself look better?",
        "Have you ever had a holiday romance?",
        "Have you ever had a festival romance?",
        "What is something you would do if you knew there were no consequences?",
        "What would you do if all crimes are legal now?",
        "What do you desire the most to do on the other player?",
        "What’s your toxic trait?",
        "Do you still have feelings for any of your exes?",
        "What’s more important you - love or money?",
        "Who do you think should pay on a first date?",
        "What nickname do you call your partner/ they call you?",
        "If you could change one thing you've done, what would it be?",
        "What is your most sensitive body part?",
        "What body part turns you on?",
        "Have you seen someone changing?",
        "What is your favorite outfit?",
        "What do you think is your sexiest outfit?",
        "What ruins a relationship for you?",
        "What is your biggest red flag?",
        "Allow the other player to ask you a question #1",
        "Allow the other player to ask you a question #2",
        "Allow the other player to ask you a question #3",
        "Allow the other player to ask you a question #4",
        "Allow the other player to ask you a question #5",
        "Allow the other player to ask you a question #6",
        "If you could swap your body with a boy/girl, what would be the first thing you do?",
        "If you could swap your body with a boy/girl, for how long will you stay?",
        "What is something you want to tell the other player but are to shy to do so?",
        "What is something you want to tell the other player but are afraid of the consequences?",
        "What is something no one knows about you?",
        "What is the biggest lie you have told?",
        "What is a secret you have not shared with anyone else?",
        "What is something you like and are too shamed to admit?",
        "If you could be invisible for a day, what’s the first thing you would do?",
        "What’s the biggest secret you’ve kept from your parents?",
        "What’s the most embarrassing music you listen to?",
        "What’s one thing you love most about yourself?",
        "Who is the last person you creeped on social media?",
        "When was the last time you wet the bed?",
        "If a genie granted you three wishes, what would you ask for and why?",
        "What excuse have you used before to get out plans?",
        "What's the longest you've ever slept?",
        "What’s the shortest you’ve ever slept?",
        "What's the longest time you've ever gone without showering?",
        "Who do you text the most?",
        "What is the biggest lie you ever told your parents?",
        "What’s an instant deal breaker in a potential love interest?",
        "What's the worst physical pain you've ever experienced?",
        "What's the worst emotional pain you have ever experienced?",
        "What's your favorite part of your body?",
        "Have you ever gone skinny dipping?",
        "What is the biggest romantic fail you’ve ever experienced.",
        "Name one thing you’d do if you knew there’d be zero consequences.",
        "When’s the last time you said you were sorry? For what?",
        "What’s the most embarrassing thing you’ve done to get a crush’s attention?",
        "What’s more important to you: love or money?",
        "What’s the last movie that made you cry?",
        "What’s the last song that made you cry?",
        "When’s the last time you got caught in a lie?",
        "What gross smell do you actually enjoy?",
        "Who was the last person you said “I love you” to?",
        "Who’s your celebrity “hall pass” if you were to meet that person while in a relationship?",
        "Have you ever cheated on an exam?",
        "What unexpected part of the body do you find attractive?",
        "What’s the most awkward thing you’ve ever been caught doing?",
        "Have you ever flirted with a close friend’s sibling?",
        "If you had to get a tattoo today, what would it be?",
        "Even if you’d be paid $1 million for it, what’s something you would never do?",
        "What popular TV show or movie do you secretly hate?",
        "What’s the most adventurous thing you’ve ever done?",
        "When have you been in the most trouble in school?",
        "If you had to always be overdressed or underdressed, which would you choose?",
        "What’s the luckiest thing that’s ever happened to you?",
        "Do you have any phobias?",
        "Do you believe in an afterlife?",
        "If you had to move to a different country tomorrow, where would you go?",
        "What do you want to be remembered for most in life?",
        "Do you believe in soul mates?",
        "Have you ever re-gifted a present? What was it?",
        "What’s the weirdest thing you do when you’re alone?",
        "What movie (or franchise) are you most embarrassed to love?",
        "Have you ever had an imaginary friend? Describe them.",
        "If you could become besties with a celebrity, who would it be?",
        "What’s the most embarrassing nickname you’ve ever been given?",
        "If you could trade lives with any person you know for a day, who would it be?",
        "What’s the worst thing you’ve ever said to anyone?",
        "What’s the scariest dream you’ve ever had?",
        "What’s the weirdest place you’ve kissed/hooked up with someone?",
        "What app do you check first in the morning?",
        "What’s the most embarrassing thing you’ve ever purchased?",
        "What’s the longest you’ve ever gone without brushing your teeth?",
        "What’s the weirdest thing you have in your bedroom?",
        "What’s the weirdest thing you have in your house?",
        "Have you ever started a rumor about someone? What was it?",
        "If you could talk to a fortune teller, what would you ask them?",
        "Do you believe in aliens? What do you think they look like?",
        "Have you ever given a fake number?",
        "Who was your first love?",
        "Who was your first crush?",
        "Who was your first heartbreak?",
        "When was your first heartbreak?",
        "What does falling in love feel like to you?",
        "Is there anyone you stalk on social media?",
        "Who are you jealous of?",
        "Have you ever been rejected by someone?",
        "Have you ever fallen in love at first sight?",
        "Do you want to get married someday?",
        "What are you most excited about at this very moment?",
        "What’s your wildest fantasy?",
        "What do you write about the most in your diary?",
        "Have you ever been in a fight?",
        "Have you ever had a wardrobe malfunction?",
        "What is the stupidest thing you have done for a crush or partner?",
        "Who is the last person you have masturbated to?",

    ];


    const bottomPhrases = [
        "Pick someone in this room and (lovingly) roast them for one minute straight.",
        "Let another person post an Instagram caption on your behalf.",
        "Hand over your phone to another player who can send a single text saying anything they want to anyone they want.",
        "Let the other players go through your phone for one minute.",
        "Say pickles at the end of every sentence you say until it's your turn again.",
        "Imitate a TikTok star until another player guesses who you're portraying.",
        "Show your best dance moves.",
        "Go outside and try to “summon” the rain as loud as possible.",
        "Serenade the person to your right for a full minute.",
        "Do 10 squats.",
        "Let the other players redo your hairstyle.",
        "Dump out your purse, backpack, or pockets and do a show and tell of what's inside.",
        "Do your sassiest runway walk.",
        "Bark like a dog until it’s your next turn.",
        "Repeat everything the person to your right says until your next turn.",
        "Demonstrate how you style your hair in the mirror (without actually using the mirror).",
        "In the next 10 minutes, find a way to scare another player and make it a surprise.",
        "Talk to a pillow as if it’s your crush.",
        "Show the oldest selfie on your phone.",
        "Go to your crush’s Instagram page and like something from several weeks ago.",
        "Find your very first crush on social media and go through their posts.",
        "Describe the most attractive quality of every person in the room.",
        "Sing like an opera singer instead of speaking for the next two minutes.",
        "Let everyone pose you in an embarrassing position and take a picture.",
        "Pretend to be underwater for the next two minutes.",
        "Make out with a pillow.",
        "Let everyone go through your Snapchat history.",
        "Let everyone go through your Instagram history.",
        "Let everyone go through your WhatsApp history.",
        "Let everyone go through your photo album.",
        "Give the person to your right a foot massage.",
        "Give the person to your right a shoulder massage.",
        "Give the person to your right a leg massage.",
        "Give the person to your right a face massage.",
        "Give the person to your right a back massage.",
        "Pretend to be a ballerina until your next turn.",
        "Serenade the person next to you.",
        "Try to fit your whole fist in your mouth.",
        "Read aloud the most personal text you’ve sent in recent days.",
        "Reveal your screen time report.",
        "Read out the last dirty text you sent",
        "Send a dirty text to someone right now",
        "Say something dirty to the person on your left",
        "Remove 2 items of clothing",
        "Remove 1 item of clothing",
        "Remove two items of clothing",
        "Remove one item of clothing",
        "Remove your shirt",
        "Remove your shoes",
        "Remove your socks",
        "Tell two truths and a lie, and other people have to guess which one the lie is",
        "Perform a seductive dance for the whole group",
        "Do an imitation of your favourite TikToker",
        "Share a picture of your current crush to the rest of the group",
        "Recount the story of a time you were aroused in a place you shouldn't.",
        "Caress yourself in a romantic fashion.",
        "Caress yourself as if you were making out.",
        "Imitate the actions of making out midair.",
        "Recount in detail a scene or setting in your favorite book.",
        "Recount in detail a scene or setting in your favorite smutty book.",
        "Describe the actions that you enjoy the most during masturbating.",
        "Describe what aroused you in a dream.",
        "Describe one of your sexual kink/desire.",
        "Describe what you would do to your crush in bed.",
        "Describe what you would do to your partner in bed.",
        "Describe what sex toy you would use on the other player.",
        "Describe your wildest fantasies.",
        "Describe one time where you were turned on in inappropriate places.",
        "Describe what object turns you on.",
        "Describe what sight turns you on.",
        "Describe what body part turns you on.",
        "Tell your favorite smutty story.",
        "Describe what you imagine when you orgasm.",
        "Describe what you imagine when you masturbate.",
        "Describe your favorite role-play scene to be in.",
        "Describe what you wish your partner does to you during sex.",

    ];

    let topUsedPhrases = [];
    let bottomUsedPhrases = [];

    function getRandomPhrase(phrases, usedPhrases) {
        if (usedPhrases.length === phrases.length) {
            // All phrases have been used, reset the used phrases array
            usedPhrases.length = 0;
        }

        let phrase;
        do {
            phrase = phrases[Math.floor(Math.random() * phrases.length)];
        } while (usedPhrases.includes(phrase));

        usedPhrases.push(phrase);
        return phrase;
    }

    document.querySelector(".panel-top").addEventListener("click", function() {
        const randomPhrase = getRandomPhrase(topPhrases, topUsedPhrases);
        document.getElementById("topModalBody").textContent = randomPhrase;
    });

    document.querySelector(".panel-bottom").addEventListener("click", function() {
        const randomPhrase = getRandomPhrase(bottomPhrases, bottomUsedPhrases);
        document.getElementById("bottomModalBody").textContent = randomPhrase;
    });
});
